"""Q: does this script's own write reach the event log, and what does one write put there?

Probe 025 read the log and never wrote to it under its own name, because on the probed site the
script's `generate_event_log_entries` was False for the 67 hours that probe ran in. Every event 025
measured was generated by somebody else. That leaves the question a caller actually has unanswered:
I made the change, is it in the feed, under whose name, and how many rows did it cost?

The flag is on the ApiUser, not on the request, so a client cannot turn it on and cannot see it fail.
Nothing errors when it is off: the write succeeds, the log stays empty, and any webhook scoped to that
change never fires. That is the silent failure this probe exists to name.

The read half reports the flag as this script can see it and tallies who generates events on the site.
The write half makes one Shot, changes one field, deletes it, and counts what each step logged.

    python probes/049_script_events.py --write

The event rows this probe generates are permanent: `DELETE /entity/event_log_entries/<id>` is refused
(probe 025). That is true of any write against this API and is not litter the probe can clean up.
"""
import json
import time

import _lib

env = _lib.load_env()
c = _lib.client()
ARR = {"Content-Type": "application/vnd+shotgun.api3_array+json"}
SCRIPT = env.get("FPT_API_SCRIPT_NAME", "")
rows = []


def search(entity, filters, fields, sort="-id", size=50):
    r = c.post(f"/entity/{entity}/_search", headers=ARR,
               json={"filters": filters, "fields": fields, "sort": sort,
                     "page": {"size": size}})
    return r, (r.json() if r.content else {})


def line(e):
    """One event, flattened. `entity` must be named in `fields` or it is absent, not null."""
    a = e["attributes"]
    rel = e.get("relationships", {})
    u = (rel.get("user") or {}).get("data") or {}
    ent = (rel.get("entity") or {}).get("data") or {}
    m = a.get("meta") or {}
    return (f"   {a.get('created_at')}  {a.get('event_type')}\n"
            f"      user={u.get('name')!r}/{u.get('type')}  "
            f"entity={ent.get('type')}:{ent.get('id')}  attribute={a.get('attribute_name')!r}\n"
            f"      session_uuid={'set' if a.get('session_uuid') else None}  "
            f"meta.type={m.get('type')!r} in_create={m.get('in_create')} "
            f"{m.get('old_value')!r} -> {m.get('new_value')!r}")


rows.append("===== the gate: ApiUser.generate_event_log_entries")

r = c.get("/schema/ApiUser/fields/generate_event_log_entries")
rows.append(f"GET /schema/ApiUser/fields/generate_event_log_entries -> {r.status_code}")
if r.ok:
    p = r.json()["data"]["properties"]
    rows.append(f"   data_type {p.get('data_type', {}).get('value')!r}  "
                f"editable {p.get('editable', {}).get('value')!r}  "
                f"default {p.get('default_value', {}).get('value')!r}")
else:
    rows.append("   " + json.dumps(r.json().get("errors"))[:400])

r, b = search("api_users", [["firstname", "is", SCRIPT]],
              ["firstname", "generate_event_log_entries", "description"])
rows.append(f"\nPOST /entity/api_users/_search on its own name -> {r.status_code}")
if r.ok and b.get("data"):
    me = b["data"][0]
    rows.append(f"   id {me['id']}  generate_event_log_entries="
                f"{me['attributes'].get('generate_event_log_entries')!r}")
    ME = me["id"]
else:
    rows.append("   " + json.dumps(b.get("errors", b))[:400])
    ME = None

rows.append("\n-- can the script see, or set, its own flag")
if ME:
    rows.append(f"   GET  /entity/api_users/{ME} -> {c.get(f'/entity/api_users/{ME}').status_code}")
    if _lib.writes_allowed():
        # The same value it already holds, so a permitted PUT still cannot change the site.
        cur = b["data"][0]["attributes"].get("generate_event_log_entries")
        pr = c.put(f"/entity/api_users/{ME}", json={"generate_event_log_entries": cur})
        rows.append(f"   PUT  the value it already has ({cur!r}) -> {pr.status_code}")
        if not pr.ok:
            rows.append("   " + json.dumps(pr.json().get("errors"))[:400])
    else:
        rows.append("   PUT  the flag: needs --write")

rows.append("\n\n===== who generates events on this site, last 24 hours")
r, b = search("event_log_entries", [["created_at", "in_last", [1, "DAY"]]],
              ["event_type", "user", "created_at"], size=500)
tally, by_type = {}, {}
for e in b.get("data", []):
    u = (e.get("relationships", {}).get("user") or {}).get("data") or {}
    k = (u.get("type"), u.get("name") == f"{SCRIPT} 1.0")
    tally[k] = tally.get(k, 0) + 1
    t = e["attributes"].get("event_type")
    by_type[t] = by_type.get(t, 0) + 1
rows.append(f"   {len(b.get('data', []))} events read")
for (kind, mine), n in sorted(tally.items(), key=lambda x: -x[1]):
    rows.append(f"   x{n:<5} user type {kind}" + ("   <- this script" if mine else ""))
rows.append("   top event types: " + json.dumps(dict(sorted(by_type.items(),
                                                            key=lambda x: -x[1])[:6])))

rows.append("\n-- the flag's own audit trail, which is how its history is readable at all")
r, b = search("event_log_entries",
              [["event_type", "is", "Shotgun_ApiUser_Change"],
               ["attribute_name", "is", "generate_event_log_entries"]],
              ["created_at", "meta"], size=100)
flips = b.get("data", [])
on = sum(1 for e in flips if (e["attributes"].get("meta") or {}).get("new_value") in (True, "True"))
rows.append(f"   {len(flips)} flips recorded, {on} of them turning it on")

if not _lib.writes_allowed():
    rows.append("\n\n===== the write half needs --write")
    _lib.emit("049_script_events", "\n".join(rows), env)
    raise SystemExit(0)

SANDBOX = _lib.sandbox_id(c, env)
rows.append("\n\n===== one create, one update, one delete, and what each logged")

st = c.get("/schema/Shot/fields/sg_status_list").json()
vals = st["data"]["properties"]["valid_values"]["value"]
EV = ["event_type", "attribute_name", "user", "session_uuid", "created_at", "meta", "entity"]


def events_for(shot_id, want, timeout=90):
    """Poll until the log has `want` rows for this Shot, or time runs out. Returns (rows, seconds)."""
    t0 = time.time()
    got = []
    while time.time() - t0 < timeout:
        r, b = search("event_log_entries",
                      [["entity", "is", {"type": "Shot", "id": shot_id}]], EV, size=100)
        got = b.get("data", [])
        if len(got) >= want:
            break
        time.sleep(2)
    return got, time.time() - t0


with _lib.Created(c) as made:
    t0 = time.time()
    shot = c.post("/entity/shots", json={
        "project": {"type": "Project", "id": SANDBOX},
        "code": "zzprobe_049_shot",
        "description": "probe 049",
        "sg_status_list": vals[0]}).json()["data"]
    made.add("shots", shot["id"])
    SHOT = shot["id"]
    rows.append(f"\n-- create: POST /entity/shots with 4 keys -> {SHOT}")

    got, waited = events_for(SHOT, 1)
    rows.append(f"   first event visible after {waited:.1f}s; {len(got)} row(s) for this Shot")
    for e in got:
        rows.append(line(e))
    n_create = len(got)

    t1 = time.time()
    pr = c.put(f"/entity/shots/{SHOT}", json={"sg_status_list": vals[1]})
    rows.append(f"\n-- update: PUT sg_status_list {vals[0]!r} -> {vals[1]!r} -> {pr.status_code}")
    got, waited = events_for(SHOT, n_create + 1)
    rows.append(f"   {len(got) - n_create} new row(s) after {waited:.1f}s")
    for e in got[:len(got) - n_create]:
        rows.append(line(e))
    n_update = len(got)

rows.append("\n-- delete: the row is retired on the way out of the block")
r, b = search("event_log_entries", [["entity", "is", {"type": "Shot", "id": SHOT}]], EV)
rows.append(f"   filtering on entity after the delete -> {len(b.get('data', []))} row(s) "
            f"(was {n_update}); `entity` goes null when the target is retired, probe 025")

r, b = search("event_log_entries",
              [["event_type", "in", ["Shotgun_Shot_Retirement", "Shotgun_Shot_Change",
                                     "Shotgun_Shot_New"]],
               ["created_at", "in_last", [1, "HOUR"]]], EV, size=100)
mine = [e for e in b.get("data", []) if
        ((e["attributes"].get("meta") or {}).get("entity_id") == SHOT)]
rows.append(f"   found by meta.entity_id instead -> {len(mine)} row(s) across the whole hour")
for e in mine[:4]:
    rows.append(line(e))
    m = e["attributes"].get("meta") or {}
    rows.append(f"      meta keys: {sorted(m)}")

rows.append(f"\n   total events for one create + one update + one delete: {len(mine)}")

_lib.emit("049_script_events", "\n".join(rows), env)
