<script>
	import { REPO } from '$lib/site.js';
</script>

<footer>
	<div class="inner">
		<p class="statement">
			Every entry on this site is the output of a probe in
			<a href="{REPO}/tree/main/probes"><code>probes/</code></a>. The corpus is generated by running
			those probes against a live Flow Production Tracking site, not written from memory.
		</p>

		<ul class="links">
			<li><a href={REPO}>GitHub</a></li>
			<li><a href="{REPO}/tree/main/corpus">The corpus</a></li>
			<li><a href="/how-it-works">How it works</a></li>
			<li>MIT, intended</li>
		</ul>

		<p class="fine">
			Not affiliated with or endorsed by Autodesk. Flow Production Tracking is their product; this is
			an independent record of how its REST API answers.
		</p>
	</div>
</footer>

<style>
	footer {
		border-top: var(--border) solid var(--rule);
		background: var(--ground-sunken);
		margin-top: var(--space-8);
	}

	.inner {
		max-width: var(--wide);
		margin-inline: auto;
		padding: var(--space-6) var(--gutter) var(--space-7);
		display: grid;
		gap: var(--space-4);
	}

	.statement {
		max-width: var(--measure);
		color: var(--ink-muted);
	}

	.links {
		list-style: none;
		padding: 0;
		display: flex;
		flex-wrap: wrap;
		gap: var(--space-2) var(--space-5);
		font-size: var(--text-sm);
	}

	.fine {
		font-size: var(--text-xs);
		color: var(--ink-muted);
		max-width: var(--measure);
	}
</style>
