<script>
	import { REPO } from '$lib/site.js';
</script>

<footer>
	<div class="col inner">
		<p class="statement">
			Every entry on this site is the output of a probe in
			<a href="{REPO}/tree/main/probes"><code>probes/</code></a>. The corpus is generated by running
			those probes against a live Flow Production Tracking site, not written from memory.
		</p>

		<ul class="links">
			<li><a href={REPO}>GitHub</a></li>
			<li><a href="{REPO}/tree/main/corpus">The corpus</a></li>
			<li><a href="/how-it-works">How it works</a></li>
			<!-- Every entry as markdown, one line each. On every page because the
			     client that wants it did not arrive at the front door. -->
			<li><a href="/llms.txt">llms.txt</a></li>
			<li>MIT, intended</li>
		</ul>

		<p class="fine">
			Not affiliated with or endorsed by Autodesk. Flow Production Tracking is their product; this is
			an independent record of how its REST API answers.
		</p>
	</div>
</footer>

<style>
	.inner {
		display: grid;
		grid-template-columns: var(--col);
		gap: var(--space-4);
		padding-block: var(--space-6) var(--space-8);
		font-size: var(--text-sm);
	}

	/* The rule spans the text, not the gutters, so it lines up with the rules
	   inside the column above it. */
	.inner::before {
		content: '';
		display: block;
		border-top: var(--border) solid var(--rule);
		margin-bottom: var(--space-2);
	}

	.statement {
		color: var(--ink-muted);
	}

	.links {
		list-style: none;
		padding: 0;
		display: flex;
		flex-wrap: wrap;
		gap: var(--space-2) var(--space-5);
	}

	.fine {
		font-size: var(--text-xs);
		color: var(--ink-muted);
	}
</style>
